### ISSUE TITLE
Scratch blocks rendering issue w/ dropdown

### ISSUE THREAD

**Issue by paulinahaduong** [GSE-CCL/scratch-to-blocks#6]
<img width="289" alt="Screenshot 2020-07-06 10 31 25" src="https://user-images.githubusercontent.com/5756274/86604813-daba2d00-bf73-11ea-936c-df250d029c32.png">
<img width="178" alt="Screenshot 2020-07-06 10 31 30" src="https://user-images.githubusercontent.com/5756274/86604825-e0177780-bf73-11ea-9fff-0d9339b516a2.png">

**Comment by jsarchibald** [comment]
Problem is here - https://github.com/GSE-CCL/scratch-to-blocks/blob/5ffa5e207fc8f5173dbe78661bc22cc567d9c113/blocks.py#L383 - need to do something separate for broadcast blocks; specifically, [{} v]

**Comment by jsarchibald** [comment]
Fixed, will be in the next scratch-tools release
